export const projects = [
  {
    title: 'The Movie Database',
    description: "Our Team Project, a full comlpete Front-Back end porject rich with great futures. Redux, node-vibrant, scraper using pupputer, carousel, ... and many other futuers",
      image: '/images/movie.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    // demo: 'https://health-companion-shadi.herokuapp.com/',
    code: 'https://github.com/Iyal-Khanjar/Frontend-Movies',
    id: 0,
  },
  {
    title: 'Health Companion',
    description: "Using React, Node.js, Express & MongoDB I built a Full Stack MERN Application - from start to finish. The App is called Health Companion and it is a simple app that allows you track and manage your healt.",
      image: '/images/signUp.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    demo: 'https://health-companion-shadi.herokuapp.com/',
    code: 'https://github.com/shakkyr/Health-App-with-MERN',
    id: 1,
  },
  {
    title: 'E-Commerce',
    description:"My small eShop app have admin and user sides will let you controll orders and do orders",
    image: '/images/eshop.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    demo: 'https://online-shop-shadi.herokuapp.com/',
    code: 'https://github.com/shakkyr/eShop-nodejs',
    id: 2,
  },
  {
    title: 'Company Manager',
    description: "The Company Manager will manage his workers: fire them aband new cars",
      image: '/images/company.png',
      tags: ['React', 'MockAPI'],
    demo: 'https://company-manager.netlify.app',
    code: 'https://github.com/shakkyr/Company-react',
    id: 3,
  },
  {
    title: 'Bank App',
    description: "our first simple code using MERN stack small app to transfare money between users",
    image: '/images/bank.png',
    tags: ['Mongo', 'Express', 'React', 'Node'],
    demo: 'https://bank-monggo-nodejs.herokuapp.com/',
    code: 'https://github.com/shakkyr/bank-nodejs-mongodb',
    id: 4,
  },
  {
    title: 'ShhhChat',
    description: "Basic chat app using react",
    image: '/images/chat.jpeg',
    tags: ['React', 'CSS', 'mockAPI'],
    demo: 'https://shhhchat-mid-tasak.netlify.app/',
    code: 'https://github.com/shakkyr/ShhhChat',
    id: 5,
  },
  {
    title: 'Amazone clone',
    description: "second week of the bootcamp cloned amazon ",
    image: '/images/amazon.jpeg',
    tags: ['CSS', 'HTML'],
    demo: 'https://shakky-amazone-clone.netlify.app/',
    code: 'https://github.com/shakkyr/amazon-clone',
    id: 6,
  },
  {
    title: 'minecraft',
    description: "first month of the bootcamp basic skills in javascript",
    image: '/images/minecraft.jpeg',
    tags: ['HTML', 'CSS', 'JAVASCRIPT'],
    demo: 'https://shakkymine-cr2d.netlify.app/',
    code: 'https://github.com/shakkyr/minecraft',
    id: 7,
  },
  {
    title: 'covid-19',
    description: "working with chart to get covid-19 data using API",
    image: '/images/covid.jpeg',
    tags: ['HTML', 'CSS', 'JAVASCRIPT'],
    demo: 'https://covid19-shakky.netlify.app/',
    code: 'https://github.com/shakkyr/minecraft',
    id: 8,
  },
];

export const TimeLineData = [
  { year: "2005", text: "Graduated, {Mas'ade High-School}", },
  { year: "2008", text: 'Computer Technical Certification', },
  { year: "2016", text: 'Mobile, Computer Technical support Certification of Social Affairs and Social Services', },
  { year: "2008-2021", text: 'Surveyor and civil engineering ', },
  { year: "2021", text: 'Full Stack Developer Bootcamp-Appleseed', },
];
